### ISSUE TITLE
Calling LoadLibraryA function does not retain ECX register

### ISSUE THREAD

**Issue by craigp1231** [PlummersSoftwareLLC/HelloAssembly#11]
Memory access violation occurs when attempting to reuse the ECX register after LoadLibrary is called.

`call dword ptr[ebp + fn_LoadLibraryA]`

When this function is called, it does not retain the ECX register. The ECX register is being used as an index for the hash location, but gets reused by the `LoadLibraryA` function, without pushing the ECX register onto the stack.

Any subsequent calls to `find_function` causes a memory access violation here...
`mov [ebp + ecx], eax                    ; save the funtion address in our table`

**Comment by rbergen** [comment]
That's not what Dave, Lasse and I are seeing, on a number of different machines. In the video, Dave shows the application starting and running.

Is this behavior you're describing based on observations you've made, or  based on knowledge about how LoadLibraryA functions?

**Comment by lassehauballe** [comment]
I will agree with @rbergen that it may come down to different machines. 

The ECX value is initially set at the beginning of resolve_symbols_kernel32. When find_function is called it is initialized with a pushad instruction, meaning all the registers are pushed to the stack including the ECX . 

When find_function reaches its end in find_function_finished all these registers are then popped back using "popad". So ECX should indeed be correct. 

Perhaps it is the case for you, that ECX is not zero when resolve_symbols_kernel32 begins?

**Comment by craigp1231** [comment]
When I pull the latest code from the Repo, it builds fine, but crashes when I attempt to run it. I used x64dbg to determine that an memory access violation occurred on the line shown above. 

If I change the assembly to push ECX onto the stack, and pop it off after the LoadLibraryA function, the application builds and runs successfully. Notice I have to pop the 3 stack pushes before the call as well. I'm not sure why if stdcall convention is being used?
`        push hash_GetStartupInfoA
        call find_function
		
		push ecx								; push the last index onto the stack

load_user32:                                    ; Push "user32.dll" onto the stack in reverse order
        push txt_ll
        push txt_32_d
        push txt_user
        push esp
        call dword ptr[ebp + fn_LoadLibraryA]

resolve_symbols_user32:
		pop ecx
		pop ecx
		pop ecx
		pop ecx									; The last index of ECX
        mov ebx, eax                            ; Load the base address of user32.dll into ebx
`

**Comment by craigp1231** [comment]
> I will agree with @rbergen that it may come down to different machines.
> 
> The ECX value is initially set at the beginning of resolve_symbols_kernel32. When find_function is called it is initialized with a pushad instruction, meaning all the registers are pushed to the stack including the ECX .
> 
> When find_function reaches its end in find_function_finished all these registers are then popped back using "popad". So ECX should indeed be correct.
> 
> Perhaps it is the case for you, that ECX is not zero when resolve_symbols_kernel32 begins?

Before the call to LoadLibraryA, ECX is 0x24
![image](https://user-images.githubusercontent.com/4073362/211027020-3d1d09ae-9783-4687-9605-c0faa662b787.png)

After the call to LoadLibraryA, ECX is 0xF90000
![image](https://user-images.githubusercontent.com/4073362/211027203-8c7b4c72-90ce-4a52-960e-286eb16ec673.png)

Which then causes an memory access violation here...
![image](https://user-images.githubusercontent.com/4073362/211027389-abceb9e3-e047-46b0-be9d-7dff37df7b2a.png)

**Comment by lassehauballe** [comment]
Perhaps, it was a bad idea to use the ECX register for this since it is a "volatile" register that is not guaranteed to stay the same after a call. But still, weird that it works for us but not for you..

**Comment by craigp1231** [comment]
Edition	Windows 10 Pro
Version	21H2
Installed on	‎29/‎05/‎2020
OS build	19044.2364
Experience	Windows Feature Experience Pack 120.2212.4190.0

**Comment by rbergen** [comment]
Maybe that's it. I run Windows 11 Pro 22H2, build 22621.963. I'm almost certain that Dave also runs a version of Windows 11.

@lassehauballe What about you?

**Comment by lassehauballe** [comment]
Yeah, I am also on Windows 11.  Same build as @rbergen.

**Comment by lassehauballe** [comment]
I think it's a matter of using a volatile register. Since the code does use pushad and popad, it should be able to change from ecx to perhaps edi. I will test it and make a proposal for change.

**Comment by rbergen** [comment]
@lassehauballe If you do create another version that aims to address this, maybe @craigp1231 can test the respective branch on your fork on Windows 10 before we move towards merging?

**Comment by lassehauballe** [comment]
https://github.com/lassehauballe/HelloAssembly

I updated my forked repository. I changed it from ecx to edi. It works on my Windows 11. 

The only problem is, that, unlike ecx, edi is not zero when we start so we lose some bytes by having to zero out the register first. Might be ways to optimize it. 

@craigp1231 Please try it and let us know :)

**Comment by craigp1231** [comment]
@lassehauballe Yup, that appears to work fine :)

**Comment by craigp1231** [comment]
@lassehauballe Actually you can reduce it by a byte just by using `mov edi, 10h`

**Comment by rbergen** [comment]
@lassehauballe Well, we gain a few bytes with the PR that I merged yesterday. Maybe we'll have to surrender a few to add Windows 10 support?

**Comment by lassehauballe** [comment]
Seems that using @craigp1231 's advice that no extra bytes are needed :) 

Please, test the version in my repository. If it works, I will make a PR.

**Comment by tostercx** [comment]
@lassehauballe yeah that fixes it for Win10 (at least on my machine)

**Comment by rbergen** [comment]
@craigp1231 Would you be able to also confirm that the current code base works for you on Windows 10? I think we can close this issue, but I'd prefer to do that knowing that it is has also been resolved for you.

**Comment by craigp1231** [comment]
@rbergen Yes, the latest commit works on Win 10. Also the PR #13  from 640-KB works fine on Win 10 as well.

**Comment by rbergen** [comment]
Thanks for confirming, and your comment about #13. We could indeed use some help with testing proposed changes on supported Windows desktop OS versions, if that's the right way to put it.
